/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./GeneScience.types";
import * as _1 from "./GeneScience.client";
import * as _2 from "./GeneScience.message-composer";
import * as _3 from "./GeneScience.react-query";
export namespace GeneScience {
  export const GeneScience = { ..._0,
    ..._1,
    ..._2,
    ..._3
  };
}