/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./DragonCore.types";
import * as _1 from "./DragonCore.client";
import * as _2 from "./DragonCore.message-composer";
import * as _3 from "./DragonCore.react-query";
export namespace DragonCore {
  export const DragonCore = { ..._0,
    ..._1,
    ..._2,
    ..._3
  };
}